name = "liberty-reach-messenger"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# D1 Database
[[d1_databases]]
binding = "DATABASE"
database_name = "liberty-reach-db"
database_id = "414477cc-8899-4ff2-be45-3174b224405d"
migrations_dir = "migrations"

# Променливи
[vars]
TURN_SECRET = "my-secret-turn-password"
MAX_MESSAGE_SIZE = 4194304
BULGARIA_EDGE = "sofia.libertyreach.internal"
LOG_LEVEL = "info"
